In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

In [3]:
print(os.listdir())

['.git', '.ipynb_checkpoints', 'assets', 'pictures', 'project_group_IOT.ipynb', 'README.md']


In [4]:
os.chdir("./assets")

In [5]:
test = pd.read_csv("test.csv")
print(test.head(1))

   id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0   1           1043     1          1.8         1  14       0           5   

   m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0    0.1        193  ...  16        226      1412  3476    12     7   

   talk_time  three_g  touch_screen  wifi  
0          2        0             1     0  

[1 rows x 21 columns]


In [6]:
train = pd.read_csv("train.csv")
print(train.head(1))

   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  

[1 rows x 21 columns]


In [7]:
print(test.columns)
print(train.columns)

Index(['id', 'battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc',
       'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc',
       'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object')
Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')


In [30]:
print(set(test.columns)-set(train.columns))
print(set(train.columns)-set(test.columns))
print(train["price_range"].describe())

{'id'}
{'price_range'}
count    2000.000000
mean        1.500000
std         1.118314
min         0.000000
25%         0.750000
50%         1.500000
75%         2.250000
max         3.000000
Name: price_range, dtype: float64


In [31]:
train_price_y = np.array(train["price_range"])
print((train_price_y))
data = train_price_y
shape = (data.size, data.max()+1)
one_hot_y = np.zeros(shape)
rows = np.arange(data.size)
one_hot_y[rows, data] = 1
print(one_hot_y)

[1 2 2 ... 3 0 3]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [21]:
test_x = test.drop(columns=["id"])
train_x = train.drop(columns=["price_range"])

In [34]:
# doing as a linear regression
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(len(train_x.columns), input_dim=len(train_x.columns), activation='relu'))
model.add(Dense(len(train_x.columns)/2, input_dim=len(train_x.columns), activation='sigmoid'))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(train_x, one_hot_y, epochs=500, batch_size=64)

Epoch 1/500
32/32 [==============================] - 0s 936us/step - loss: 1.6537 - accuracy: 0.2885
Epoch 2/500
32/32 [==============================] - 0s 935us/step - loss: 1.5242 - accuracy: 0.3847
Epoch 3/500
32/32 [==============================] - 0s 968us/step - loss: 1.3966 - accuracy: 0.4339
Epoch 4/500
32/32 [==============================] - 0s 968us/step - loss: 1.3794 - accuracy: 0.4286
Epoch 5/500
32/32 [==============================] - 0s 1000us/step - loss: 1.3056 - accuracy: 0.4517
Epoch 6/500
32/32 [==============================] - 0s 968us/step - loss: 1.2780 - accuracy: 0.4215
Epoch 7/500
32/32 [==============================] - 0s 968us/step - loss: 1.2269 - accuracy: 0.4452
Epoch 8/500
32/32 [==============================] - 0s 968us/step - loss: 1.1903 - accuracy: 0.4447
Epoch 9/500
32/32 [==============================] - 0s 968us/step - loss: 1.1770 - accuracy: 0.4585
Epoch 10/500
32/32 [==============================] - 0s 968us/step - loss: 1.1505 - accur

32/32 [==============================] - 0s 1ms/step - loss: 0.9111 - accuracy: 0.6088
Epoch 82/500
32/32 [==============================] - 0s 968us/step - loss: 1.0576 - accuracy: 0.5238
Epoch 83/500
32/32 [==============================] - 0s 1000us/step - loss: 0.9352 - accuracy: 0.5790
Epoch 84/500
32/32 [==============================] - 0s 935us/step - loss: 0.9173 - accuracy: 0.5786
Epoch 85/500
32/32 [==============================] - 0s 839us/step - loss: 0.9183 - accuracy: 0.5901
Epoch 86/500
32/32 [==============================] - 0s 839us/step - loss: 0.9544 - accuracy: 0.5626
Epoch 87/500
32/32 [==============================] - 0s 839us/step - loss: 0.9547 - accuracy: 0.5714
Epoch 88/500
32/32 [==============================] - 0s 871us/step - loss: 0.9361 - accuracy: 0.5669
Epoch 89/500
32/32 [==============================] - 0s 871us/step - loss: 0.9033 - accuracy: 0.5894
Epoch 90/500
32/32 [==============================] - 0s 903us/step - loss: 0.8958 - accuracy: 0

32/32 [==============================] - 0s 935us/step - loss: 0.7169 - accuracy: 0.7067
Epoch 162/500
32/32 [==============================] - 0s 968us/step - loss: 0.6943 - accuracy: 0.7041
Epoch 163/500
32/32 [==============================] - 0s 903us/step - loss: 0.6798 - accuracy: 0.7183
Epoch 164/500
32/32 [==============================] - 0s 903us/step - loss: 0.7078 - accuracy: 0.7193
Epoch 165/500
32/32 [==============================] - 0s 936us/step - loss: 0.7156 - accuracy: 0.6960
Epoch 166/500
32/32 [==============================] - 0s 1ms/step - loss: 0.7187 - accuracy: 0.7027
Epoch 167/500
32/32 [==============================] - 0s 1ms/step - loss: 0.7330 - accuracy: 0.6805
Epoch 168/500
32/32 [==============================] - 0s 1ms/step - loss: 0.7167 - accuracy: 0.7018
Epoch 169/500
32/32 [==============================] - 0s 1ms/step - loss: 0.7323 - accuracy: 0.6701
Epoch 170/500
32/32 [==============================] - 0s 1ms/step - loss: 0.7231 - accuracy: 0

Epoch 241/500
32/32 [==============================] - 0s 903us/step - loss: 0.6777 - accuracy: 0.7043
Epoch 242/500
32/32 [==============================] - 0s 871us/step - loss: 0.7140 - accuracy: 0.6952
Epoch 243/500
32/32 [==============================] - 0s 871us/step - loss: 0.6720 - accuracy: 0.7059
Epoch 244/500
32/32 [==============================] - 0s 871us/step - loss: 0.6704 - accuracy: 0.7087
Epoch 245/500
32/32 [==============================] - 0s 903us/step - loss: 0.6366 - accuracy: 0.7148
Epoch 246/500
32/32 [==============================] - 0s 903us/step - loss: 0.7382 - accuracy: 0.6376
Epoch 247/500
32/32 [==============================] - 0s 871us/step - loss: 0.7120 - accuracy: 0.6780
Epoch 248/500
32/32 [==============================] - 0s 935us/step - loss: 0.7395 - accuracy: 0.6575
Epoch 249/500
32/32 [==============================] - 0s 903us/step - loss: 0.7143 - accuracy: 0.6949
Epoch 250/500
32/32 [==============================] - 0s 903us/step - lo

32/32 [==============================] - 0s 1ms/step - loss: 0.6643 - accuracy: 0.7007
Epoch 321/500
32/32 [==============================] - 0s 1ms/step - loss: 0.6691 - accuracy: 0.7063
Epoch 322/500
32/32 [==============================] - 0s 1ms/step - loss: 0.6737 - accuracy: 0.7058
Epoch 323/500
32/32 [==============================] - 0s 1ms/step - loss: 0.6244 - accuracy: 0.7291
Epoch 324/500
32/32 [==============================] - 0s 1ms/step - loss: 0.6492 - accuracy: 0.7200
Epoch 325/500
32/32 [==============================] - 0s 968us/step - loss: 0.6418 - accuracy: 0.7228
Epoch 326/500
32/32 [==============================] - 0s 935us/step - loss: 0.6247 - accuracy: 0.7318
Epoch 327/500
32/32 [==============================] - 0s 903us/step - loss: 0.6524 - accuracy: 0.6929
Epoch 328/500
32/32 [==============================] - 0s 1000us/step - loss: 0.6321 - accuracy: 0.7359
Epoch 329/500
32/32 [==============================] - 0s 1000us/step - loss: 0.6285 - accuracy:

32/32 [==============================] - 0s 1ms/step - loss: 0.6341 - accuracy: 0.7058
Epoch 401/500
32/32 [==============================] - 0s 1ms/step - loss: 0.6302 - accuracy: 0.7244
Epoch 402/500
32/32 [==============================] - 0s 968us/step - loss: 0.5930 - accuracy: 0.7438
Epoch 403/500
32/32 [==============================] - 0s 1000us/step - loss: 0.5941 - accuracy: 0.7402
Epoch 404/500
32/32 [==============================] - 0s 935us/step - loss: 0.6854 - accuracy: 0.6931
Epoch 405/500
32/32 [==============================] - 0s 1ms/step - loss: 0.6419 - accuracy: 0.7048
Epoch 406/500
32/32 [==============================] - 0s 1ms/step - loss: 0.6324 - accuracy: 0.7357
Epoch 407/500
32/32 [==============================] - 0s 1000us/step - loss: 0.6132 - accuracy: 0.7356
Epoch 408/500
32/32 [==============================] - 0s 968us/step - loss: 0.6150 - accuracy: 0.7423
Epoch 409/500
32/32 [==============================] - 0s 871us/step - loss: 0.6416 - accurac

Epoch 480/500
32/32 [==============================] - 0s 871us/step - loss: 0.5940 - accuracy: 0.7537
Epoch 481/500
32/32 [==============================] - 0s 903us/step - loss: 0.6018 - accuracy: 0.7346
Epoch 482/500
32/32 [==============================] - 0s 871us/step - loss: 0.6404 - accuracy: 0.7292
Epoch 483/500
32/32 [==============================] - 0s 839us/step - loss: 0.6245 - accuracy: 0.7506
Epoch 484/500
32/32 [==============================] - 0s 839us/step - loss: 0.6131 - accuracy: 0.7590
Epoch 485/500
32/32 [==============================] - 0s 839us/step - loss: 0.6062 - accuracy: 0.7469
Epoch 486/500
32/32 [==============================] - 0s 871us/step - loss: 0.6363 - accuracy: 0.7252
Epoch 487/500
32/32 [==============================] - 0s 871us/step - loss: 0.6190 - accuracy: 0.7378
Epoch 488/500
32/32 [==============================] - 0s 881us/step - loss: 0.6161 - accuracy: 0.7527
Epoch 489/500
32/32 [==============================] - 0s 903us/step - lo

In [ ]:
# from sklearn.metrics import accuracy_score
# a = accuracy_score(pred,test)
# print('Accuracy is:', a*100)

In [ ]:
!pip list